const { fontFamily } = require("tailwindcss/defaultTheme");

/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "app/**/*.{ts,tsx}",
    "components/**/*.{ts,tsx}",
    "pages/**/*.{ts,tsx}",
  ],
  theme: {
    container: {
      center: true,
      screens: {
        sm: "640px",
        md: "768px",
        lg: "1024px",
        xl: "1200px",
        "2xl": "1536px",
      },
      padding: {
        DEFAULT: "1rem",
        md: "1.5rem",
        lg: "2rem",
      },
    },
    extend: {
      colors: {
        backgroundPrimary: "var(--backgroundPrimary)",
        backgroundSecondary: "var(--backgroundSecondary)",
        backgroundDisabled: "var(--backgroundDisabled)",
        backgroundTertiary: "var(--backgroundTertiary)",
        backgroundHighlight: "var(--backgroundHighlight)",
        backgroundIcon: "var(--backgroundIcon)",
        backgroundBrandPrimary: "var(--backgroundBrandPrimary)",
        backgroundBrandSecondary: "var(--backgroundBrandSecondary)",
        backgroundAlert: "var(--backgroundAlert)",
        backgroundPrimaryReversed: "var(--backgroundPrimaryReversed)",
        backgroundBrandPrimaryReversed: "var(--backgroundBrandPrimaryReversed)",
        backgroundSelected: "var(--backgroundSelected)",
        backgroundBrandTertiary: "var(--backgroundBrandTertiary)",
        contentPrimary: "var(--contentPrimary)",
        contentSecondary: "var(--contentSecondary)",
        contentActive: "var(--contentActive)",
        contentAccent: "var(--contentAccent)",
        contentDisabled: "var(--contentDisabled)",
        contentWarning: "var(--contentWarning)",
        contentPositive: "var(--contentPositive)",
        contentNegative: "var(--contentNegative)",
        contentTertiary: "var(--contentTertiary)",
        contentAction: "var(--contentAction)",
        contentInactive: "var(--contentInactive)",
        contentInformation: "var(--contentInformation)",
        contentVisited: "var(--contentVisited)",
        contentPrimaryReversed: "var(--contentPrimaryReversed)",
        contentActionReversed: "var(--contentActionReversed)",
        contentVisitedReversed: "var(--contentVisitedReversed)",
        contentInput: "var(--contentInput)",
        borderPrimary: "var(--borderPrimary)",
        borderSecondary: "var(--borderSecondary)",
        borderTertiary: "var(--borderTertiary)",
        borderActive: "var(--borderActive)",
        borderInactive: "var(--borderInactive)",
        borderNegative: "var(--borderNegative)",
        borderWarning: "var(--borderWarning)",
        borderPositive: "var(--borderPositive)",
        borderInformation: "var(--borderInformation)",
        borderPrimaryReversed: "var(--borderPrimaryReversed)",
        borderSeparator: "var(--borderSeparator)",
        decorativeDesertSand: "var(--decorativeDesertSand)",
        decorativeGreyGoose: "var(--decorativeGreyGoose)",
        decorativeWispPink: "var(--decorativeWispPink)",
        decorativeLinen: "var(--decorativeLinen)",
        decorativeBlue: "var(--decorativeBlue)",
        decorativeViolet: "var(--decorativeViolet)",
        decorativeBurntOrange: "var(--decorativeBurntOrange)",
        decorativeBurntorange20: "var(--decorativeBurntorange20)",
        decorativeWhite20: "var(--decorativeWhite20)",
        decorativeViolet20: "var(--decorativeViolet20)",
        hoverPrimary: "var(--hoverPrimary)",
        activePrimary: "var(--activePrimary)",

        /** custom */
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
      },
      fontSize: {
        xs: "var(--fontSizeTextXs)",
        sm: "var(--fontSizeTextSm)",
        base: "var(--fontSizeTextBase)",
        lg: "var(--fontSizeTextLg)",
        xl: "var(--fontSizeTextXl)",
        "2xl": "var(--fontSizeText2xl)",
        "3xl": "var(--fontSizeText3xl)",
        "4xl": "var(--fontSizeText4xl)",
        "5xl": "var(--fontSizeText5xl)",
        "6xl": "var(--fontSizeText6xl)",
        "7xl": "var(--fontSizeText7xl)",
        "8xl": "var(--fontSizeText8xl)",
        "9xl": "var(--fontSizeText9xl)",
      },
      letterSpacing: {
        "tracking-normal": "var(--letterSpacingTrackingNormal)",
        "tracking-wider": "var(--letterSpacingTrackingWider)",
        "tracking-wide": "var(--letterSpacingTrackingWide)",
        "tracking-tight": "var(--letterSpacingTrackingTight)",
        "tracking-tighter": "var(--letterSpacingTrackingTighter)",
        "tracking-widest": "var(--letterSpacingTrackingWidest)",
      },
      lineHeight: {
        "leading-none": "var(--lineHeightsLeadingNone)",
        "leading-tight": "var(--lineHeightsLeadingTight)",
        "leading-snug": "var(--lineHeightsLeadingSnug)",
        "leading-normal": "var(--lineHeightsLeadingNormal)",
        "leading-relaxed": "var(--lineHeightsLeadingRelaxed)",
        "leading-loose": "var(--lineHeightsLeadingLoose)",
        "leading-3": "var(--lineHeightsLeading3)",
        "leading-4": "var(--lineHeightsLeading4)",
        "leading-5": "var(--lineHeightsLeading5)",
        "leading-6": "var(--lineHeightsLeading6)",
        "leading-7": "var(--lineHeightsLeading7)",
        "leading-8": "var(--lineHeightsLeading8)",
        "leading-9": "var(--lineHeightsLeading9)",
        "leading-10": "var(--lineHeightsLeading10)",
      },
      fontWeight: {
        thin: "var(--fontWeightFontThin)",
        extralight: "var(--fontWeightFontExtralight)",
        light: "var(--fontWeightFontLight)",
        normal: "var(--fontWeightFontNormal)",
        medium: "var(--fontWeightFontMedium)",
        semibold: "var(--fontWeightFontSemibold)",
        bold: "var(--fontWeightFontBold)",
        extrabold: "var(--fontWeightFontExtrabold)",
        black: "var(--fontWeightFontBlack)",
      },
      fontFamily: {
        sans: ["var(--font-inter)", ...fontFamily.sans],
        serif: ["var(--font-serif)", ...fontFamily.serif],
        sansDm: ["var(--font-dm-sans)", ...fontFamily.serif]
      },
      borderRadius: {
        "rounded-none": "var(--borderRadiusRoundedNone)",
        "rounded-sm": "var(--borderRadiusRoundedSm)",
        rounded: "var(--borderRadiusRounded)",
        "rounded-md": "var(--borderRadiusRoundedMd)",
        "rounded-lg": "var(--borderRadiusRoundedLg)",
        "rounded-xl": "var(--borderRadiusRoundedXl)",
        "rounded-2xl": "var(--borderRadiusRounded2xl)",
        "rounded-3xl": "var(--borderRadiusRounded3xl)",
        "rounded-full": "var(--borderRadiusRoundedFull)",
      },
      borderWidth: {
        DEFAULT: "var(--borderWidthBorder)",
        0: "var(--borderWidthBorder0)",
        2: "var(--borderWidthBorder2)",
        4: "var(--borderWidthBorder4)",
        8: "var(--borderWidthBorder8)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: 0 },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: 0 },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
      gridTemplateColumns: {
        // 24 column grid
        24: "repeat(24, minmax(0, 1fr))",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
