/**
 * Do not edit directly
 * Generated on Mon, 12 Jun 2023 06:00:55 GMT
 */

export const backgroundPrimary = "#d9d9d9";
export const backgroundSecondary = "#f5f5f5";
export const backgroundDisabled = "#ebebeb";
export const backgroundTertiary = "#EEEEEE";
export const backgroundHighlight = "#FFE58F";
export const backgroundIcon = "#000000";
export const backgroundBrandPrimary = "#231F20";
export const backgroundBrandSecondary = "#"; // Not in use
export const backgroundAlert = "#"; // Not in use
export const backgroundPrimaryReversed = "#000000";
export const backgroundBrandPrimaryReversed = "#fff";
export const backgroundSelected = "#FCFCFC";
export const contentPrimary = "#000000e0";
export const contentSecondary = "rgba(0,0,0,0.65)";
export const contentActive = "#ffffff";
export const contentAccent = "#ff4d4f";
export const contentDisabled = "rgba(0,0,0,0.25)";
export const contentWarning = "#FAAD14";
export const contentPositive = "#52C41A";
export const contentNegative = "#DF1642";
export const contentTertiary = "#000000";
export const contentAction = "#";
export const contentInactive = "#";
export const contentInformation = "#";
export const contentVisited = "#";
export const contentPrimaryReversed = "#fff";
export const contentActionReversed = "#";
export const contentVisitedReversed = "#";
export const contentInput = "#9E9E9E";
export const borderPrimary = "#9e9e9e";
export const borderSecondary = "#000000";
export const borderTertiary = "#fff";
export const borderActive = "#000000";
export const borderInactive = "#"; // Not in use
export const borderNegative = "#FF4D4F";
export const borderWarning = "#faad14";
export const borderPositive = "#52c41a";
export const borderInformation = "#"; // Not in use
export const borderPrimaryReversed = "#";
export const borderSeparator = "#EEEEEE";
export const decorativeDesertSand = "#e0cfb5";
export const decorativeGreyGoose = "#c8d0d0";
export const decorativeWispPink = "#fcf5f5";
export const decorativeLinen = "#fcf0e7";
export const hoverPrimary = "#000000";
export const activePrimary = "#000000";
export const fontFamiliesFuturaPt = "futura-pt";
export const fontFamiliesAdobeGaramondPro = "adobe-garamond-pro";
export const lineHeightsLeadingNone = "1"; // 1
export const lineHeightsLeadingTight = "1.25"; // 1.25
export const lineHeightsLeadingSnug = "1.375"; // 1.375
export const lineHeightsLeadingNormal = "1.5"; // 1.5
export const lineHeightsLeadingRelaxed = "1.625"; // 1.625
export const lineHeightsLeading3 = "12px";
export const lineHeightsLeadingLoose = "2";
export const lineHeightsLeading4 = "16px";
export const lineHeightsLeading5 = "22px";
export const lineHeightsLeading8 = "32px";
export const lineHeightsLeading6 = "24px";
export const lineHeightsLeading7 = "28px";
export const lineHeightsLeading9 = "32px";
export const lineHeightsLeading10 = "40px";
export const fontWeightFontThin = "100";
export const fontWeightFontExtralight = "200";
export const fontWeightFontLight = "300";
export const fontWeightFontNormal = "400";
export const fontWeightFontMedium = "500";
export const fontWeightFontSemibold = "600";
export const fontWeightFontBold = "700";
export const fontWeightFontExtrabold = "800";
export const fontWeightFontBlack = "900";
export const fontWeightItalic = "Italic";
export const fontSizeTextXs = "12px";
export const fontSizeTextSm = "14px";
export const fontSizeTextBase = "16px";
export const fontSizeTextLg = "18px";
export const fontSizeTextXl = "20px";
export const fontSizeText2xl = "24px";
export const fontSizeText3xl = "30px";
export const fontSizeText4xl = "32px";
export const fontSizeText5xl = "40px";
export const fontSizeText6xl = "48px";
export const fontSizeText7xl = "72px";
export const fontSizeText8xl = "96px";
export const fontSizeText9xl = "128px";
export const letterSpacingTrackingNormal = "0em";
export const letterSpacingTrackingWider = "0.1em";
export const letterSpacingTrackingWide = "0.05em";
export const letterSpacingTrackingTight = "-0.025em";
export const letterSpacingTrackingTighter = "-0.05em";
export const letterSpacingTrackingWidest = "0.2em";
export const textCaseNone = "none";
export const textCaseUppercase = "uppercase";
export const textDecorationNone = "none";
export const textDecorationUnderline = "underline";
export const textDecorationLineThrough = "line-through";
export const paragraphIndent0 = "0px";
export const borderRadiusRoundedNone = "0px";
export const borderRadiusRoundedSm = "2px";
export const borderRadiusRounded = "4px";
export const borderRadiusRoundedMd = "6px";
export const borderRadiusRoundedLg = "8px";
export const borderRadiusRoundedXl = "12px";
export const borderRadiusRounded2xl = "16px";
export const borderRadiusRounded3xl = "24px";
export const borderRadiusRoundedFull = "9999px";
export const borderWidthBorder = "1px";
export const borderWidthBorder0 = "0";
export const borderWidthBorder2 = "2px";
export const borderWidthBorder4 = "4px";
export const borderWidthBorder8 = "8px";
